import {test,expect} from '@playwright/test';
test('SOS, emergency forms and daily routine fit mobile and desktop',async({page})=>{
 await page.route('**/api/**',r=>r.fulfill({json:[]}));
 await page.route('**/api/status',r=>r.fulfill({json:{setup:false,registration:true}}));
 await page.route('**/api/me',r=>r.fulfill({json:{id:'qa',nombre:'QA',familia:'QA',rol:'superadmin',subscription:{commercial_exempt:1},platform_controls:{blocked_modules:[]}}}));
 await page.route('**/api/children',r=>r.fulfill({json:[{id:'qa-child',primer_nombre:'Prueba',fecha_nacimiento:'2020-01-01'}]}));
 const day=new Intl.DateTimeFormat('es-CL',{weekday:'long',timeZone:'America/Santiago'}).format(new Date());
 const schedule=[{id:'block',dia:day,hora_inicio:'08:00',hora_fin:'09:00',actividad:'Actividad de prueba',materiales:'Cuaderno y agua'}];
 await page.route('**/api/records/horario_escolar?*',r=>r.fulfill({json:schedule}));
 await page.goto('/');
 await expect(page.getByText('Actividad de prueba',{exact:true})).toBeVisible();
 await expect(page.getByText('Materiales / recordatorios: Cuaderno y agua',{exact:true})).toBeVisible();
 await page.getByRole('navigation').getByRole('button',{name:'Salud',exact:true}).click();
 await page.getByRole('button',{name:'Dosis SOS / Enfermedad',exact:true}).click();
 await page.getByRole('button',{name:'Registrar Dosis SOS / Episodio de enfermedad',exact:true}).click();
 await expect(page.getByLabel('Temperatura corporal (°C, opcional)',{exact:true})).toBeVisible();
 await page.setViewportSize({width:375,height:812});
 await page.screenshot({path:'../work/care-sos-mobile.png'});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Cerrar',exact:true}).click();
 await page.getByRole('button',{name:'Urgencias',exact:true}).click();
 await page.locator('.record-section').getByRole('button',{name:'Agregar',exact:true}).click();
 await expect(page.getByLabel('Indicaciones / tratamiento al alta',{exact:true})).toBeVisible();
 await expect(page.getByText('Archivos de este registro',{exact:true})).toBeVisible();
 await page.screenshot({path:'../work/care-urgent-mobile.png'});
 await page.getByRole('button',{name:'Cerrar',exact:true}).click();
 await page.setViewportSize({width:1280,height:900});
 await page.getByRole('navigation').getByRole('button',{name:'Escolar',exact:true}).click();
 await page.getByRole('button',{name:'Horario / Rutina diaria',exact:true}).click();
 await page.locator('.record-section').getByRole('button',{name:'Agregar',exact:true}).click();
 await expect(page.getByLabel('Hora de inicio',{exact:true})).toBeVisible();
 await expect(page.getByLabel('Asignatura o actividad',{exact:true})).toBeVisible();
 await page.screenshot({path:'../work/care-routine-desktop.png'});
});
