import {test,expect} from '@playwright/test';
for(const width of [375,1280])test(`profile and consultation conditional fields persist at ${width}px`,async({page})=>{
 page.setDefaultTimeout(10000);
 let child:any=null,visit:any={id:'qa-visit',nino_id:'qa-child',fecha:'2026-11-01T15:00:00Z',medico_nombre:'Profesional QA',especialidad:'Neurología',acompanante:''};
 await page.setViewportSize({width,height:900});
 await page.route('**/api/**',r=>r.fulfill({json:[]}));
 await page.route('**/api/status',r=>r.fulfill({json:{setup:false,registration:true}}));
 await page.route('**/api/subscription',r=>r.fulfill({json:{subscription_status:'active',commercial_exempt:1}}));
 await page.route('**/api/me',r=>r.fulfill({json:{id:'qa-user',nombre:'QA',familia:'QA',rol:'editor',permisos_json:JSON.stringify({acciones:['crear','editar','eliminar']}),subscription:{subscription_status:'active',commercial_exempt:1},platform_controls:{blocked_modules:[]}}}));
 await page.route('**/api/children',async r=>{
  if(r.request().method()==='POST'){child={...r.request().postDataJSON(),id:'qa-child'};await r.fulfill({status:201,json:{id:child.id}});}
  else await r.fulfill({json:child?[child]:[]});
 });
 await page.route('**/api/children/qa-child',async r=>{child={...child,...r.request().postDataJSON()};await r.fulfill({json:{ok:true}});});
 await page.route('**/api/records/consultas_medicas?*',r=>r.fulfill({json:[visit]}));
 await page.route('**/api/records/consultas_medicas/qa-visit?*',async r=>{visit={...visit,...r.request().postDataJSON()};await r.fulfill({json:{ok:true}});});
 const section=async(name:string)=>{if(width<760)await page.getByRole('button',{name:'Abrir menú',exact:true}).click();await page.locator('.sidebar').getByRole('button',{name,exact:true}).click();};
 await page.goto('/');await page.getByRole('button',{name:'Crear primer perfil',exact:true}).click();
 let modal=page.getByRole('dialog',{name:'Nuevo perfil',exact:true});
 await modal.getByLabel('Nombre',{exact:true}).fill('Niño QA');await modal.getByLabel('Fecha de nacimiento',{exact:true}).fill('2020-01-01');
 await modal.getByLabel('¿Con quién vive?',{exact:true}).selectOption('__other');
 await modal.getByLabel('Especifica con quién vive',{exact:true}).fill('Tía y abuela');
 await expect(modal.getByLabel('Motivo de hospitalización',{exact:true})).toHaveCount(0);
 await modal.getByLabel('¿Ha estado hospitalizado/a?',{exact:true}).selectOption('Sí');
 await modal.getByLabel('Motivo de hospitalización',{exact:true}).fill('Antecedente QA');await modal.getByLabel('Tiempo de estadía',{exact:true}).fill('3 días');
 await modal.getByLabel('¿Ha estado hospitalizado/a?',{exact:true}).selectOption('No');
 await expect(modal.getByLabel('Tiempo de estadía',{exact:true})).toHaveCount(0);
 await modal.getByLabel('¿Ha estado hospitalizado/a?',{exact:true}).selectOption('Sí');
 await expect(modal.getByLabel('Tiempo de estadía',{exact:true})).toHaveValue('3 días');
 await modal.getByRole('button',{name:'Guardar',exact:true}).click();await expect(modal).toHaveCount(0);
 await section('Perfil');await expect(page.getByText('Tía y abuela',{exact:true})).toBeVisible();await expect(page.getByText('Antecedente QA',{exact:true})).toBeVisible();
 await page.reload();await section('Perfil');await page.getByRole('button',{name:'Editar perfil',exact:true}).click();
 modal=page.getByRole('dialog',{name:'Editar perfil',exact:true});await expect(modal.getByLabel('Especifica con quién vive',{exact:true})).toHaveValue('Tía y abuela');
 await modal.getByLabel('¿Ha estado hospitalizado/a?',{exact:true}).selectOption('No');await modal.getByRole('button',{name:'Guardar',exact:true}).click();
 await expect(page.getByText('Antecedente QA',{exact:true})).toHaveCount(0);expect(child.hospitalizacion_motivo).toBe('Antecedente QA');
 await section('Salud');await page.getByRole('button',{name:'Consultas médicas',exact:true}).click();
 await page.locator('.record-card').getByRole('button',{name:'Editar',exact:true}).click();
 modal=page.getByRole('dialog',{name:'Consultas médicas',exact:true});
 await expect(modal.getByLabel('Especialidad',{exact:true})).toHaveValue('__other');await expect(modal.getByLabel('Especifica la especialidad',{exact:true})).toHaveValue('Neurología');
 await modal.getByLabel('Acompañante',{exact:true}).selectOption('__other');await modal.getByLabel('Especifica el acompañante',{exact:true}).fill('Tía');
 await modal.getByRole('button',{name:'Guardar',exact:true}).click();await expect(modal).toHaveCount(0);
 expect(visit.especialidad).toBe('Neurología');await expect(page.locator('.record-card').getByText('Tía',{exact:true})).toBeVisible();
 await page.locator('.record-card').getByRole('button',{name:'Editar',exact:true}).click();
 modal=page.getByRole('dialog',{name:'Consultas médicas',exact:true});
 await modal.getByLabel('Especialidad',{exact:true}).selectOption('Enfermería');
 await expect(modal.getByLabel('Especifica la especialidad',{exact:true})).toHaveCount(0);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await modal.getByRole('button',{name:'Guardar',exact:true}).click();expect(visit.especialidad).toBe('Enfermería');
});
