import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { localEnv } from "../server/local.js";
import { handle } from "../server/api.js";
import {password} from '../server/security.js';
test("platform admin manages operational controls without bypassing clinical isolation", async () => {
  const env = localEnv(mkdtempSync(join(tmpdir(), "luspace-platform-")));
  let cookie = "";
  async function call(path, method="GET",data) {
    const r = await handle(new Request("http://localhost:5173/api/"+path,{method,headers:{origin:"http://localhost:5173",cookie,"Content-Type":"application/json"},body:data===undefined?undefined:JSON.stringify(data)}),env);
    if(r.headers.get("set-cookie")) cookie=r.headers.get("set-cookie").split(";")[0];
    return {status:r.status,body:await r.json()};
  }
  try {
    assert.equal((await call("platform/overview")).status,401);
    await call("setup","POST",{nombre:"QA",familia:"Familia QA",correo:"platform@example.test",password:"QaPassword!2026"});
    const me=(await call("me")).body;
    assert.equal(me.platform_admin,false);
    assert.equal(me.platform_setup_available,false);
    assert.equal((await call("platform/overview")).status,401);
    await env.DB.prepare("INSERT INTO familias(id,nombre) VALUES('other','Familia B')").run();
    await env.DB.prepare("INSERT INTO ninos(id,familia_id,primer_nombre,fecha_nacimiento) VALUES('secret-child','other','SECRET-CHILD','2020-01-01')").run();
    await env.DB.prepare("INSERT INTO administradores_plataforma(usuario_id) VALUES(?)").bind(me.id).run();
    assert.equal((await call("me")).body.platform_admin,true);
    assert.equal((await call("me")).body.platform_setup_available,true);
    assert.equal((await call("platform/overview")).status,401);
    assert.equal((await call("platform/enroll","POST",{correo:"admin@example.test",current_password:"QaPassword!2026",password:"AdminPassword!2026"})).status,201);
    assert.equal((await call("me")).body.platform_setup_available,false);
    assert.equal((await call("platform/enroll","POST",{correo:"admin@example.test",current_password:"QaPassword!2026",password:"AdminPassword!2026"})).status,409);
    const familyCookie=cookie;
    assert.equal((await call("platform/login","POST",{correo:"admin@example.test",password:"wrong"})).status,401);
    assert.equal((await call("platform/login","POST",{correo:"admin@example.test",password:"AdminPassword!2026"})).status,200);
    const adminCookie=cookie;
    assert.equal((await call("me")).status,401);
    const overview=await call("platform/overview");
    assert.equal(overview.status,200);
    assert.equal(overview.body.totals.familias,2);
    assert.ok(!JSON.stringify(overview.body).includes("SECRET-CHILD"));
    assert.deepEqual(Object.keys(overview.body.families[0]).sort(),["id","nombre","created_at","miembros_activos","archivos","storage_used_bytes","trial_ends_at","storage_limit_bytes","commercial_exempt","subscription_status"].sort());
    assert.ok(overview.body.statuses.length>0);
    assert.equal((await call('platform/overview?days=999')).status,400);
    assert.equal((await call('platform/overview?days=90')).status,200);
    cookie=familyCookie;
    assert.equal((await call("records/medicamentos?child=secret-child")).status,404);
    assert.equal((await call("children/secret-child","PUT",{primer_nombre:"MODIFIED"})).status,404);
    cookie=adminCookie;
    assert.equal((await call("platform/overview","POST",{})).status,404);
    assert.equal((await call("platform/children")).status,404);
    assert.equal((await env.DB.prepare("SELECT count(*) AS n FROM auditoria_plataforma").first()).n,3);
    const detail=await call('platform/families/other');
    assert.equal(detail.status,200);assert.ok(!JSON.stringify(detail.body).includes('SECRET-CHILD'));
    assert.equal((await call('platform/families/missing')).status,404);
    const controls={nombre:'Familia B',subscription_status:'active',trial_ends_at:null,storage_limit_bytes:52428800,commercial_exempt:true,blocked_modules:['salud'],ai_enabled:false,uploads_enabled:false,reports_enabled:false,reason:'QA operación autorizada',admin_password:'AdminPassword!2026'};
    assert.equal((await call('platform/families/other','PUT',{...controls,admin_password:'wrong'})).status,401);
    assert.equal((await call('platform/families/other','PUT',{...controls,reason:''})).status,400);
    assert.equal((await call('platform/families/other','PUT',{...controls,blocked_modules:['not-a-module']})).status,400);
    assert.equal((await call('platform/families/other','PUT',controls)).status,200);
    for(const [id,role] of [['other-owner','superadmin'],['other-editor','editor']]) {
      await env.DB.prepare('INSERT INTO usuarios(id,familia_id,nombre,correo,rol) VALUES(?,?,?,?,?)').bind(id,'other',id,id+'@example.test',role).run();
      await env.DB.prepare('INSERT INTO credenciales_usuario(usuario_id,password_hash) VALUES(?,?)').bind(id,await password('FamilyPassword!2026')).run();
    }
    const userPath='platform/families/other/users/other-editor/';
    const auth={reason:'Soporte de acceso solicitado',admin_password:'AdminPassword!2026'};
    assert.equal((await call('platform/families/'+me.familia_id+'/users/'+me.id+'/reset-password','POST',{...auth,new_password:'NewPassword!2026'})).status,403);
    assert.equal((await call('platform/families/other/users/'+me.id+'/reset-password','POST',{...auth,new_password:'NewPassword!2026'})).status,404);
    assert.equal((await call('platform/families/other/users/other-owner/active','POST',{...auth,active:false})).status,409);
    assert.equal((await env.DB.prepare("SELECT activo FROM usuarios WHERE id='other-owner'").first()).activo,1);
    await call('login','POST',{correo:'other-editor@example.test',password:'FamilyPassword!2026'});
    const editorCookie=cookie;
    assert.equal((await call('platform/families/other','PUT',controls)).status,401);
    assert.equal((await call('records/medicamentos?child=secret-child')).status,403);
    assert.equal((await call('export','POST',{child:'secret-child',modules:['perfil']})).status,403);
    assert.equal((await call('consultation/preview','POST',{child:'secret-child',modules:['perfil']})).status,403);
    assert.equal((await call('files?child=secret-child&module=perfil','POST',{})).status,403);
    assert.equal((await call('me')).body.platform_controls.uploads_enabled,false);
    cookie=adminCookie;
    assert.equal((await call(userPath+'reset-password','POST',{...auth,new_password:'short'})).status,400);
    assert.equal((await call(userPath+'reset-password','POST',{...auth,new_password:'NewPassword!2026'})).status,200);
    cookie=editorCookie;assert.equal((await call('me')).status,401);
    assert.equal((await call('login','POST',{correo:'other-editor@example.test',password:'FamilyPassword!2026'})).status,401);
    assert.equal((await call('login','POST',{correo:'other-editor@example.test',password:'NewPassword!2026'})).status,200);
    const changedCookie=cookie;
    cookie=adminCookie;
    assert.equal((await call(userPath+'active','POST',{...auth,active:false})).status,200);
    cookie=changedCookie;assert.equal((await call('me')).status,401);
    cookie=adminCookie;
    assert.equal((await call(userPath+'active','POST',{...auth,active:true})).status,200);
    assert.equal((await call('platform/families/other','PUT',controls)).status,429);
    // Simulate the rate-limit window ending in this isolated test database.
    await env.DB.prepare('DELETE FROM intentos_acceso WHERE clave=?').bind('platform-change:'+me.id).run();
    assert.equal((await call(userPath+'close-sessions','POST',auth)).status,200);
    assert.equal((await call('platform/families/other','PUT',{...controls,blocked_modules:[],ai_enabled:true,uploads_enabled:true,reports_enabled:true})).status,200);
    cookie=familyCookie;
    assert.equal((await call('records/medicamentos?child=secret-child')).status,404);
    cookie=adminCookie;
    const audits=await env.DB.prepare("SELECT descripcion FROM auditoria_plataforma WHERE accion='RESET_FAMILY_PASSWORD'").all();
    assert.ok(audits.results.length);assert.ok(!JSON.stringify(audits).includes('NewPassword!2026'));assert.ok(!JSON.stringify(audits).includes('AdminPassword!2026'));
    await env.DB.prepare("UPDATE administradores_plataforma SET activo=0 WHERE usuario_id=?").bind(me.id).run();
    assert.equal((await call("platform/overview")).status,401);
    cookie=familyCookie;
    assert.equal((await call("me")).body.platform_admin,false);
  } finally {env.close();}
});
