import {useEffect,useState} from 'react';
import {Files,Search,Eye,Download,RefreshCw,FileText} from 'lucide-react';
import {api,dateLabel,type Row} from './lib';
import {ErrorNote,Modal} from './components';
import {fetchAttachment,downloadAttachment} from './fileAccess';
import {modules} from '../shared/models.js';
import './my-files.css';
function FilePreview({file,close}:{file:Row;close:()=>void}){
 const [url,setUrl]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();let object='';fetchAttachment(file.id,controller.signal).then(blob=>{if(!controller.signal.aborted){object=URL.createObjectURL(blob);setUrl(object);}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>{controller.abort();if(object)URL.revokeObjectURL(object);};},[file.id]);
 return <Modal title={file.nombre} description={file.origen} close={close}><ErrorNote error={error}/>{!error&&!url&&<p role="status">Abriendo documento…</p>}{url&&(file.mime.startsWith('image/')?<img className="my-file-image" src={url} alt={file.nombre}/>:<div className="pdf-preview-card"><FileText/><p>Documento PDF</p><a className="secondary" href={url} target="_blank" rel="noopener noreferrer">Abrir PDF</a></div>)}</Modal>;
}
export default function MyFiles({children:profiles}:{children:Row[]}){
 const [q,setQ]=useState(''),[child,setChild]=useState(''),[module,setModule]=useState(''),[type,setType]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0);
 const [data,setData]=useState<Row|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[preview,setPreview]=useState<Row|null>(null),[downloading,setDownloading]=useState('');
 useEffect(()=>{let live=true;setBusy(true);setError('');setData(null);const timer=setTimeout(()=>{const params=new URLSearchParams({q,child,module,type,page:String(page)});api('file-index?'+params).then(result=>{if(live)setData(result);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setBusy(false);});},200);return()=>{live=false;clearTimeout(timer);};},[q,child,module,type,page,revision]);
 const filter=(setter:(v:string)=>void,value:string)=>{setter(value);setPage(1);};
 async function download(file:Row){setError('');setDownloading(file.id);try{await downloadAttachment(file.id,file.nombre);}catch(e){setError((e as Error).message);}finally{setDownloading('');}}
 return <section className="my-files"><div className="my-files-heading"><div><h1><Files/> Mis archivos</h1><p className="muted">Documentos de tu familia, según tus permisos.</p></div><button className="secondary" disabled={busy} onClick={()=>setRevision(revision+1)}><RefreshCw size={17}/> Actualizar</button></div><div className="my-files-filters"><label><span><Search size={16}/> Buscar</span><input type="search" value={q} onChange={e=>filter(setQ,e.target.value)} placeholder="Nombre del archivo o sección"/></label><label>Niño/a<select value={child} onChange={e=>filter(setChild,e.target.value)}><option value="">Todos</option>{profiles.map(n=><option key={n.id} value={n.id}>{n.primer_nombre}</option>)}</select></label><label>Sección<select value={module} onChange={e=>filter(setModule,e.target.value)}><option value="">Todas</option>{Object.entries(modules).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Tipo<select value={type} onChange={e=>filter(setType,e.target.value)}><option value="">Todos</option><option value="pdf">PDF</option><option value="image">Imágenes</option></select></label></div><ErrorNote error={error}/>{busy?<p role="status">Consultando archivos…</p>:<><p className="muted">{data?.total??0} archivos disponibles</p><div className="my-files-list">{data?.items.map((file:Row)=><article className="my-file-row" key={file.id}><FileText className="my-file-icon"/><div className="my-file-info"><h2 title={file.nombre}>{file.nombre}</h2><p>{file.nino_nombre} · {file.origen}</p><small>{dateLabel(file.created_at)} · {file.bytes>=1048576?(file.bytes/1048576).toFixed(2)+' MB':(file.bytes/1024).toFixed(1)+' KB'}</small></div><div className="my-file-actions"><button className="secondary" aria-label={'Ver '+file.nombre} onClick={()=>setPreview(file)}><Eye size={17}/> Ver</button>{file.can_download&&<button className="secondary" disabled={!!downloading} aria-label={'Descargar '+file.nombre} onClick={()=>void download(file)}><Download size={17}/>{downloading===file.id?'Descargando…':'Descargar'}</button>}</div></article>)}</div>{data&&!data.items.length&&<p>No hay archivos para estos filtros.</p>}<div className="my-files-pages"><button className="secondary" disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</button><span>Página {page}</span><button className="secondary" disabled={!data||page*data.page_size>=data.total} onClick={()=>setPage(page+1)}>Siguiente</button></div></>}{preview&&<FilePreview file={preview} close={()=>setPreview(null)}/>}</section>;
}
