import {useEffect,useState} from 'react';
import {Gauge,HardDrive,Database,Brain,ShieldCheck,RefreshCw,AlertTriangle} from 'lucide-react';
import {ResponsiveContainer,PieChart,Pie,Cell,Tooltip} from 'recharts';
import {api,type Row} from './lib';
import {ErrorNote} from './components';
import './platform-consumption.css';
const bytes=(n:number)=>n>=1e9?(n/1e9).toFixed(2)+' GB':n>=1e6?(n/1e6).toFixed(2)+' MB':n>=1000?(n/1000).toFixed(1)+' KB':n+' bytes';
export default function PlatformConsumption(){
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);try{setData(await api('platform/consumption'));setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);
 return <section className="platform-consumption"><article className="card platform-consumption-heading"><div><h2><Gauge size={22}/> Consumo global y alertas</h2><p className="muted">Control interno de LuSpace. Todas las familias, sin contenido clínico.</p></div><button disabled={busy} onClick={()=>void load()}><RefreshCw size={17}/> Actualizar consumo</button></article><ErrorNote error={error}/>{busy&&<p role="status">Actualizando consumo…</p>}{data&&<>
 <div className="platform-chart-grid"><article className="card platform-chart-card"><h2><HardDrive size={20}/> Reserva global de archivos</h2><div className="platform-donut"><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={[{name:'Usado y reservado',value:Math.min(data.storage.committed_bytes,data.storage.limit_bytes)},{name:'Disponible',value:Math.max(0,data.storage.limit_bytes-data.storage.committed_bytes)}]} dataKey="value" nameKey="name" innerRadius={70} outerRadius={98} isAnimationActive={false}><Cell fill="#14b8a6"/><Cell fill="#e5eaf1"/></Pie><Tooltip formatter={(v:any)=>bytes(Number(v))}/></PieChart></ResponsiveContainer><div className="platform-donut-center"><strong>{(data.storage.committed_bytes/data.storage.limit_bytes*100).toFixed(2)}%</strong><small>del límite interno</small></div></div><p className="consumption-total"><strong>{bytes(data.storage.committed_bytes)}</strong> de {bytes(data.storage.limit_bytes)}</p><ul className="consumption-facts"><li>Archivos registrados <b>{data.storage.files}</b></li><li>Subidas reservadas <b>{bytes(data.storage.reserved_bytes)}</b></li><li>Metadatos apuntando a R2 <b>{bytes(data.storage.r2_metadata_bytes)}</b></li><li>Referencia R2 Standard <b>10 GB-mes</b></li></ul><p className="muted">Margen interno de 2 GB. La referencia gratuita no es una cuota contratada ni una medición de facturación.</p></article>
 <article className="card platform-chart-card"><h2><ShieldCheck size={20}/> Protección activa</h2><p className={'consumption-state state-'+data.storage.level}>{data.storage.uploads_blocked?'Nuevas subidas bloqueadas':'Subidas sujetas a cuota familiar y global'}</p><p>Las subidas se reservan antes de escribir en R2. Ni una familia exenta puede superar el límite global.</p><p>Lectura, descarga y eliminación siguen disponibles según los permisos. No se borran documentos al alcanzar el límite.</p><ul className="consumption-thresholds">{[70,85,95].map(n=><li key={n}><AlertTriangle size={16}/><strong>{n}%</strong><span>{n===70?'Aviso preventivo':n===85?'Revisar capacidad':'Alerta crítica'}</span></li>)}</ul>{data.storage.reservation_count>0&&<p role="status" className="consumption-warning">{data.storage.reservation_count} reservas pendientes: pueden ser subidas en curso o interrumpidas. No se liberan automáticamente; requieren revisión técnica.</p>}<p className="muted">El límite protege los archivos gestionados por esta app. Otros buckets, objetos sin metadatos y operaciones de Cloudflare no están incluidos.</p></article></div>
 <div className="platform-chart-grid"><article className="card platform-chart-card"><h2><Database size={20}/> D1: originales de adjuntos</h2><p className="consumption-total"><strong>{bytes(data.d1.attachment_bytes)}</strong> / {bytes(data.d1.attachment_limit_bytes)}</p><progress max={data.d1.attachment_limit_bytes} value={data.d1.attachment_bytes} aria-label="Reserva de adjuntos en D1"/><p className="muted">Solo el contenido binario conservado en D1. No incluye registros, índices ni el tamaño físico total. El tope interno detiene nuevas cargas por D1, no las subidas a R2.</p><p>Tamaño real de la base: <strong>No disponible</strong></p></article><article className="card platform-chart-card"><h2><Brain size={20}/> Workers AI</h2><p className="consumption-total"><strong>{data.ai.requests_today}</strong> / {data.ai.daily_request_limit} solicitudes hoy</p><progress max={data.ai.daily_request_limit} value={data.ai.requests_today} aria-label="Solicitudes diarias de IA"/><p className="muted">Límite interno compartido; día en UTC. Al agotarse se ofrece el resumen básico, sin servicio de pago alternativo.</p><p>Neuronas facturables: <strong>No disponible</strong></p></article></div>
 <article className="card platform-chart-card"><h2>Uso por familia</h2><p className="muted">Las 20 familias con mayor uso. El total global incluye todas.</p><div className="consumption-families">{data.families.map((f:Row)=><div key={f.id}><div><strong>{f.nombre}</strong><span>{f.files} archivos · {bytes(f.bytes)} · {f.commercial_exempt?'cuota familiar no aplicada':bytes(f.storage_limit_bytes)+' de cuota'}</span></div><progress max={f.commercial_exempt?data.storage.limit_bytes:Math.max(f.storage_limit_bytes,1)} value={f.bytes} aria-label={'Consumo de '+f.nombre}/></div>)}</div></article>
 <article className="card platform-chart-card"><h2>Consumo informado por Cloudflare</h2><p className="muted">Sin conexión de analítica de cuenta: estas métricas no se estiman a partir de los documentos.</p><div className="consumption-unavailable">{['Almacenamiento total de la cuenta','Operaciones R2 Clase A / B','Filas leídas / escritas en D1','Peticiones de Workers'].map(label=><div key={label}><span>{label}</span><strong>No disponible</strong></div>)}</div><p className="consumption-warning">No es una garantía de cero cargos. Revisa también el consumo y la facturación de tu cuenta en Cloudflare.</p><a href="https://dash.cloudflare.com/" target="_blank" rel="noopener noreferrer">Abrir Cloudflare ↗</a><p className="muted">Actualizado: {new Date(data.generated_at).toLocaleString('es-CL')}</p></article>
 </>}</section>;
}
