import {useEffect,useState} from 'react';
import {DatabaseBackup,ShieldCheck,AlertTriangle,RefreshCw,ExternalLink,HardDrive,FileCheck2} from 'lucide-react';
import {api,dateLabel,type Row} from './lib';
import {ErrorNote} from './components';
const states:Row={pending:'Pendiente de activar',failed:'Requiere revisión',stale:'Copia desactualizada',running:'Respaldo en curso',verified:'Respaldo verificado'};
export default function PlatformBackups(){
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){setBusy(true);setError('');try{setData(await api('platform/backups'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void refresh();},[]);
 const backup=data?.last_verified;
 return <section className="platform-dashboard"><div className="platform-page-heading"><div><p className="eyebrow">PROTECCIÓN DE DATOS</p><h1><DatabaseBackup size={28}/> Respaldos y recuperación</h1><p className="muted">Resumen operativo, sin mostrar información clínica ni claves de cifrado.</p></div><button className="secondary" onClick={()=>void refresh()} disabled={busy}><RefreshCw size={17}/>{busy?'Actualizando…':'Actualizar'}</button></div><ErrorNote error={error}/>
 {data&&<><article className="card"><h2>{data.state==='verified'?<ShieldCheck size={22}/>:<AlertTriangle size={22}/>} {states[data.state]}</h2><p>Objetivo: una copia diaria cifrada; siete días de retención en R2. Los horarios pueden retrasarse y un fallo requiere atención.</p>{data.stale&&<p className="error">No hay una copia verificada en las últimas 36 horas. No considerar la protección completa todavía.</p>}<div className="actions"><a className="secondary" href={data.workflow_url} target="_blank" rel="noreferrer"><ExternalLink size={16}/> Ejecutar o revisar respaldo en GitHub</a></div></article>
 <div className="platform-kpis"><article className="card"><ShieldCheck/><h3>Última copia verificada</h3><strong>{backup?dateLabel(backup.completed_at):'Sin copia verificada'}</strong></article><article className="card"><FileCheck2/><h3>Adjuntos comprobados</h3><strong>{backup?.verified_files??'—'}</strong></article><article className="card"><DatabaseBackup/><h3>Último ensayo aislado</h3><strong>{backup?.restore_test_at?dateLabel(backup.restore_test_at):'Pendiente'}</strong></article><article className="card"><HardDrive/><h3>Copia cifrada</h3><strong>{backup?(backup.encrypted_bytes/1048576).toFixed(2)+' MiB':'—'}</strong></article></div>
 <article className="card"><h2>Recuperación segura</h2><p>Se comprueban SHA-256, autenticación AES-256-GCM, referencias familiares, filas y adjuntos. El ensayo reconstruye una base aislada y revoca las sesiones e invitados heredados.</p><p>La copia independiente en GitHub contiene solo archivos cifrados y se conserva un día. R2 conserva siete días; ambas necesitan la clave privada para recuperarse. Estado de copia independiente: <strong>{backup?.independent_copy==='verified'?'Registrada':backup?.independent_copy==='failed'?'Falló':'Pendiente'}</strong>.</p><p>No se ofrece un botón para sobrescribir producción. Una recuperación real requiere un procedimiento controlado y una nueva comprobación de permisos.</p></article>
 <article className="card"><h2>Límites preventivos</h2><p>Máximo 100 MB por copia, 1 GB para el depósito de respaldos y umbral preventivo de 8 GB entre los buckets de la cuenta al iniciar la copia. Si se supera un límite, el respaldo se detiene y avisa; no se contratan planes.</p><p className="muted">Estos controles no garantizan una factura de $0: deben revisarse también operaciones, otros servicios y consumo ajeno a LuSpace.</p></article>
 <article className="card"><h2>Historial de respaldos</h2>{!data.runs.length?<p>Aún no hay ejecuciones registradas. Configura LUSPACE_BACKUP_KEY en GitHub Secrets y ejecuta el workflow de respaldo.</p>:<div style={{overflowX:'auto'}}><table><thead><tr><th>Fecha</th><th>Estado</th><th>Archivos</th><th>Ensayo</th><th>Detalle operativo</th></tr></thead><tbody>{data.runs.map((r:Row)=><tr key={r.id}><td>{dateLabel(r.started_at)}</td><td>{r.status==='verified'?'Verificado':r.status==='running'?'En curso':'Fallido'}</td><td>{r.verified_files}</td><td>{r.restore_test_at?'Comprobado':'Pendiente'}</td><td>{r.error_code||'—'}</td></tr>)}</tbody></table></div>}</article></>}
 </section>;
}
