import {useEffect,useState,type FormEvent} from 'react';
import {Receipt,Gift,CheckCircle2,XCircle,RefreshCw,Clock} from 'lucide-react';
import {api,dateLabel,type Row} from './lib';
import {Modal,ErrorNote} from './components';
import './platform-payments.css';
const money=(n:number)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n);
function estimatedEnd(until:string|undefined,record:Row){const start=new Date(Math.max(Date.now(),Date.parse(until||'')||0)),end=new Date(start);if(record.tipo==='cortesia')end.setUTCDate(end.getUTCDate()+record.dias_cortesia);else{const day=end.getUTCDate();end.setUTCDate(1);end.setUTCMonth(end.getUTCMonth()+1);const last=new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth()+1,0)).getUTCDate();end.setUTCDate(Math.min(day,last));}return end.toISOString();}
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const labels:Record<string,string>={pendiente:'Pendiente',confirmado:'Confirmado',rechazado:'Rechazado'};
export default function PlatformPayments(){
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[family,setFamily]=useState(''),[status,setStatus]=useState(''),[form,setForm]=useState<Row|null>(null),[review,setReview]=useState<Row|null>(null),[password,setPassword]=useState(''),[verified,setVerified]=useState(false);
 async function load(){setData(await api('platform/manual-payments'));}
 useEffect(()=>{let live=true;api('platform/manual-payments').then(r=>{if(live)setData(r);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 function open(kind:string){setError('');setPassword('');setVerified(false);setReview(null);setForm({tipo:kind,familia_id:family,monto_clp:kind==='transferencia'?5938:0,fecha_pago:today(),referencia:'',notas:'',dias_cortesia:kind==='cortesia'?7:0,cuota_bytes:0,request_key:crypto.randomUUID()});}
 function edit(k:string,v:unknown){setForm(f=>f&&({...f,[k]:v}));}
 async function submit(e:FormEvent){e.preventDefault();if(!form)return;setBusy(true);setError('');try{
   const r=review?await api('platform/manual-payments/'+review.id+'/review','POST',{estado:review.action,notas:form.notas,bank_verified:verified,admin_password:password}):await api('platform/manual-payments','POST',{...form,admin_password:password});
   setForm(null);setReview(null);setPassword('');await load();setNotice(r.estado==='confirmado'?'Acceso confirmado hasta '+dateLabel(r.periodo_fin)+'.':r.estado==='rechazado'?'Registro rechazado. El acceso no cambió.':'Registro pendiente. Confirma el ingreso bancario antes de activar el acceso.');
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const families=(data?.families||[]).filter((f:Row)=>f.nombre.toLowerCase().includes(search.toLowerCase()));
 const payments=(data?.payments||[]).filter((p:Row)=>(!family||p.familia_id===family)&&(!status||p.estado===status)&&p.familia_nombre.toLowerCase().includes(search.toLowerCase()));
 const selected=(data?.families||[]).find((f:Row)=>f.id===(review?.familia_id||form?.familia_id));
 return <section className="platform-dashboard platform-payments"><div className="platform-page-heading"><div><p className="eyebrow">ADMINISTRACIÓN PRIVADA</p><h1><Receipt/> Pagos y acceso</h1><p className="muted">Transferencias y cortesías por familia. No crea ni cancela suscripciones de Mercado Pago.</p></div><button disabled={busy} onClick={()=>{setError('');load().catch(e=>setError(e.message));}}><RefreshCw size={17}/> Actualizar</button></div>
 <ErrorNote error={!form?error:''}/>{notice&&<p className="card" role="status">{notice}</p>}
 <div className="card payment-toolbar"><span><Clock size={18}/> {data?.pending??'…'} registros pendientes</span><button className="primary" disabled={!data} onClick={()=>open('transferencia')}><Receipt size={18}/> Registrar transferencia</button><button disabled={!data} onClick={()=>open('cortesia')}><Gift size={18}/> Dar días de cortesía</button></div>
 <div className="card payment-filters"><label className="field">Buscar familia<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre de la familia"/></label><label className="field">Familia<select value={family} onChange={e=>setFamily(e.target.value)}><option value="">Todas</option>{families.map((f:Row)=><option key={f.id} value={f.id}>{f.nombre}</option>)}</select></label><label className="field">Estado<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>
 <article className="card"><h2>Acceso de las familias</h2><div className="payment-family-grid">{families.filter((f:Row)=>!family||family===f.id).map((f:Row)=><div key={f.id}><strong>{f.nombre}</strong><p>{f.commercial_exempt?'Acceso exento':f.subscription_status==='trial'?'En prueba':f.subscription_status==='active'?'Activa':'Revisar acceso'}</p><small>Período manual hasta: {f.manual_paid_until?dateLabel(f.manual_paid_until):'Sin período manual'}</small><small>Cuota asignada: {(f.storage_limit_bytes/1048576).toFixed(0)} MiB</small></div>)}</div></article>
 <article className="card"><h2>Historial de transferencias y cortesías</h2><p className="muted">Últimos {data?.limit||200} registros. Una cortesía no es un pago. El historial confirmado no se elimina.</p>{!payments.length&&<p className="muted">No hay registros para estos filtros.</p>}
 {payments.map((p:Row)=><details key={p.id} className="payment-record"><summary><span><strong>{p.familia_nombre}</strong><small>{dateLabel(p.fecha_pago)} · {p.tipo==='cortesia'?p.dias_cortesia+' días de cortesía':money(p.monto_clp)+' · Transferencia'}</small></span><span className={'payment-status '+p.estado}>{labels[p.estado]}</span></summary><div className="payment-record-body"><p>Referencia: {p.referencia||'Sin referencia'}</p><p>{p.notas}</p>{p.notas_revision&&<p>Revisión: {p.notas_revision}</p>}{p.periodo_fin&&<p>Acceso: {dateLabel(p.periodo_inicio)} → {dateLabel(p.periodo_fin)}</p>}{p.cuota_bytes>0&&<p>Cuota al confirmar: {p.cuota_bytes/1048576} MiB</p>}{p.estado==='pendiente'&&<div className="payment-actions"><button className="primary" onClick={()=>{setError('');setPassword('');setVerified(false);setReview({...p,action:'confirmado'});setForm({notas:p.notas});}}><CheckCircle2 size={17}/> {p.tipo==='cortesia'?'Autorizar cortesía':'Confirmar pago y activar un mes'}</button><button onClick={()=>{setError('');setPassword('');setReview({...p,action:'rechazado'});setForm({notas:''});}}><XCircle size={17}/> Rechazar</button></div>}</div></details>)}</article>
 {form&&<Modal title={review?(review.action==='confirmado'?'Confirmar acceso':'Rechazar registro'):(form.tipo==='cortesia'?'Registrar cortesía':'Registrar transferencia')} close={()=>{if(!busy){setForm(null);setPassword('');setError('');}}}><form onSubmit={submit}><ErrorNote error={error}/><fieldset disabled={busy}>
 {!review&&<><label className="field">Familia<select required value={form.familia_id} onChange={e=>edit('familia_id',e.target.value)}><option value="">Selecciona una familia</option>{(data?.families||[]).filter((f:Row)=>!f.commercial_exempt).map((f:Row)=><option key={f.id} value={f.id}>{f.nombre}</option>)}</select></label><div className="payment-filters"><label className="field">Fecha<input type="date" required max={today()} value={form.fecha_pago} onChange={e=>edit('fecha_pago',e.target.value)}/></label>{form.tipo==='cortesia'?<label className="field">Días de cortesía<input type="number" min="1" max="90" step="1" required value={form.dias_cortesia} onChange={e=>edit('dias_cortesia',Number(e.target.value))}/></label>:<label className="field">Monto recibido (CLP)<input type="number" min="1" max="1000000000" step="1" required value={form.monto_clp} onChange={e=>edit('monto_clp',Number(e.target.value))}/></label>}</div><label className="field">Referencia bancaria (opcional)<input maxLength={120} value={form.referencia} onChange={e=>edit('referencia',e.target.value)}/></label><label className="field">Cuota de almacenamiento al confirmar<select value={form.cuota_bytes} onChange={e=>edit('cuota_bytes',Number(e.target.value))}><option value={0}>Mantener cuota actual{selected?' ('+(selected.storage_limit_bytes/1048576).toFixed(0)+' MiB)':''}</option>{[50,100,500,1024].map(m=><option key={m} value={m*1048576}>{m===1024?'1 GiB':m+' MiB'}</option>)}</select></label><p className="muted">Registrar no activa el acceso. Después revisa y confirma. Un mes se agrega al período manual vigente; si venció, comienza al confirmar.</p></>}
 {review&&<><p><strong>{review.familia_nombre}</strong> · {review.tipo==='cortesia'?review.dias_cortesia+' días sin cargo':money(review.monto_clp)}</p>{review.action==='confirmado'&&<p>Vencimiento estimado: <strong>{dateLabel(estimatedEnd(selected?.manual_paid_until,review))}</strong>. Se recalcula al confirmar.</p>}<p className="muted">Esta acción no modifica contratos automáticos. No confirmes una transferencia que también corresponda a un pago de Mercado Pago.</p>{review.action==='confirmado'&&<label className="payment-check"><input type="checkbox" required checked={verified} onChange={e=>setVerified(e.target.checked)}/>{review.tipo==='cortesia'?'Autorizo estos días de cortesía.':'Verifiqué que el dinero llegó a la cuenta bancaria. Un comprobante por sí solo no basta.'}</label>}</>}
 <label className="field">{review?'Motivo de la revisión':'Observación / motivo'}<textarea required minLength={5} maxLength={1000} value={form.notas} onChange={e=>edit('notas',e.target.value)}/></label><label className="field">Contraseña administrativa<input type="password" required maxLength={128} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" type="submit">{busy?'Guardando…':review?(review.action==='confirmado'?'Confirmar acceso':'Rechazar registro'):'Registrar como pendiente'}</button></fieldset></form></Modal>}
 </section>;
}
