import {useEffect,useState} from 'react';
import {Bell,Check,RefreshCw,ArrowRight} from 'lucide-react';
import {api,type Row} from './lib';
import {Modal,ErrorNote} from './components';
import './platform-consumption.css';
export default function PlatformNotifications({navigate}:{navigate:(section:string)=>void}){
 const [data,setData]=useState<Row|null>(null),[open,setOpen]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){try{setData(await api('platform/notifications'));setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void refresh();const tick=()=>{if(!document.hidden)void refresh();};const timer=setInterval(tick,120000);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',tick);};},[]);
 async function mark(keys:string[]){if(!keys.length)return;setBusy(true);try{await api('platform/notifications/read','POST',{keys});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><button type="button" className="platform-bell" aria-label={'Notificaciones'+(data?.unread?' · '+data.unread+' sin leer':'')} title="Notificaciones" onClick={()=>{setOpen(true);void refresh();}}><Bell size={21}/>{!!data?.unread&&<span className="platform-bell-count">{data.unread>99?'99+':data.unread}</span>}{!!error&&!data&&<span className="platform-bell-count">!</span>}</button>{open&&<Modal title="Notificaciones de plataforma" description="Familias nuevas y alertas operativas. Sin datos clínicos." close={()=>setOpen(false)}><div className="platform-notifications"><ErrorNote error={error}/><div className="actions"><button disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16}/> Actualizar</button><button disabled={busy||!data?.unread} onClick={()=>void mark(data!.items.filter((i:Row)=>!i.read).map((i:Row)=>i.key))}><Check size={16}/> Marcar todas como leídas</button></div>{!data&&!error&&<p role="status">Cargando notificaciones…</p>}{data&&<><p className="muted">{data.unread} sin leer · {data.scope}</p>{!data.items.length&&<p>Sin notificaciones por ahora.</p>}<ul>{data.items.map((item:Row)=><li key={item.key} className={'notification-'+item.severity+(item.read?' is-read':'')}><div><strong>{item.title}</strong>{!item.read&&<span className="notification-new">Nuevo</span>}<p>{item.detail}</p>{item.created_at&&<small>{new Date(item.created_at).toLocaleDateString('es-CL')}</small>}</div><div className="notification-actions"><button onClick={()=>{setOpen(false);navigate(item.target);}}><ArrowRight size={15}/> Ver sección</button>{!item.read&&<button disabled={busy} aria-label={'Marcar como leído: '+item.title} onClick={()=>void mark([item.key])}><Check size={15}/> Leído</button>}</div></li>)}</ul></>}</div></Modal>}</>;
}
