import {useEffect, useState, type FormEvent} from 'react';
import {ListTodo, Plus, Pencil, Trash2, CalendarClock, ChevronRight} from 'lucide-react';
import {api, type Row} from './lib';
import {Modal, ErrorNote} from './components';
import './reminders.css';

const localDate=(value:string)=>{if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export default function Reminders({children:profiles=[], selectedChild='', readonly=false, compact=false, onViewAll}:{children?:Row[];selectedChild?:string;readonly?:boolean;compact?:boolean;onViewAll?:()=>void}) {
  const [data,setData]=useState<{rows:Row[];members:Row[];actions:string[]}>({rows:[],members:[],actions:[]});
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[completed,setCompleted]=useState(false),[filter,setFilter]=useState(''),[edit,setEdit]=useState<Row|null>(null),[remove,setRemove]=useState<Row|null>(null);
  async function refresh(){const result=await api('reminders');setData(result);}
  async function retry(){setError('');setLoading(true);try{await refresh();}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
  useEffect(()=>{let live=true;api('reminders').then(result=>{if(live)setData(result);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
  const can=(action:string)=>!readonly&&data.actions.includes(action);
  async function mutate(path:string,method:string,body:Row){setBusy(true);setError('');try{await api(path,method,body);await refresh();setEdit(null);setRemove(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function save(e:FormEvent){e.preventDefault();if(!edit)return;const {id,version,titulo,categoria,nino_id,responsable_id,notas,fecha}=edit;await mutate(id?'reminders/'+id:'reminders',id?'PUT':'POST',{version,titulo,categoria,nino_id:nino_id||null,responsable_id:responsable_id||null,notas,fecha:fecha?new Date(fecha).toISOString():null});}
  const rows=data.rows.filter(r=>Boolean(r.completado)===completed&&(!(compact?selectedChild:filter)||!r.nino_id||r.nino_id===(compact?selectedChild:filter))).sort((a,b)=>completed?String(b.completado_at||'').localeCompare(a.completado_at||''):String(a.fecha||'9999').localeCompare(b.fecha||'9999'));
  const shown=compact?rows.slice(0,3):rows;
  return <section className={'reminders-panel '+(compact?'reminders-compact':'')}>
    <div className="reminders-heading"><h2><ListTodo size={22}/>Recordatorios</h2>{compact?<button className="link-button" onClick={onViewAll}>Ver todos<ChevronRight size={16}/></button>:can('crear')&&<button className="primary" onClick={()=>setEdit({titulo:'',categoria:'Otro',fecha:'',nino_id:filter,responsable_id:'',notas:''})}><Plus size={18}/>Nuevo recordatorio</button>}</div>
    {!compact&&<div className="reminders-tools"><div role="group" aria-label="Estado de recordatorios"><button className={!completed?'active':''} onClick={()=>setCompleted(false)}>Pendientes</button><button className={completed?'active':''} onClick={()=>setCompleted(true)}>Completados</button></div><label>Perfil<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Toda la familia</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.primer_nombre} {p.apellidos}</option>)}</select></label></div>}
    <ErrorNote error={error}/>
    {error&&!edit&&!remove&&<button disabled={loading||busy} onClick={()=>void retry()}>Actualizar lista</button>}
    {loading?<p role="status">Cargando recordatorios…</p>:!error&&!shown.length?<p className="muted">{completed?'Todavía no hay recordatorios completados.':'No hay recordatorios pendientes.'}</p>:<ul className="reminders-list">{shown.map(r=>{const overdue=!r.completado&&r.fecha&&Date.parse(r.fecha)<Date.now();return <li key={r.id} className={overdue?'overdue':''}><input type="checkbox" checked={!!r.completado} disabled={!can('editar')||busy} aria-label={'Marcar '+r.titulo+(r.completado?' como pendiente':' como completado')} onChange={()=>void mutate('reminders/'+r.id,'PATCH',{completado:!r.completado,version:r.version})}/><div className="reminder-copy"><strong>{r.titulo}</strong><div className="reminder-meta"><span>{r.categoria}</span><span>{r.nino_nombre||'Toda la familia'}</span>{r.responsable_nombre&&<span>{r.responsable_nombre}</span>}</div><small className="reminder-date"><CalendarClock size={14}/>{r.fecha?new Date(r.fecha).toLocaleString('es-CL',{dateStyle:'medium',timeStyle:'short'}):'Sin fecha'}{overdue&&<b>Vencido</b>}</small>{!compact&&r.notas&&<details><summary>Ver notas</summary><p>{r.notas}</p></details>}</div>{!compact&&<div className="reminder-actions">{can('editar')&&<button disabled={busy} aria-label={'Editar '+r.titulo} onClick={()=>setEdit({...r,fecha:localDate(r.fecha)})}><Pencil size={17}/></button>}{can('eliminar')&&<button disabled={busy} aria-label={'Eliminar '+r.titulo} onClick={()=>setRemove(r)}><Trash2 size={17}/></button>}</div>}</li>;})}</ul>}
    {edit&&<Modal title={edit.id?'Editar recordatorio':'Nuevo recordatorio'} description="Aviso dentro de LuSpace; no envía notificaciones al teléfono." close={()=>{if(!busy)setEdit(null);}} className="reminder-modal"><form onSubmit={save}><ErrorNote error={error}/><label>Título<input required maxLength={180} value={edit.titulo} placeholder="Ej. Llevar informe a la consulta" onChange={e=>setEdit({...edit,titulo:e.target.value})}/></label><div className="reminder-form-grid"><label>Fecha y hora (opcional)<input type="datetime-local" value={edit.fecha} onChange={e=>setEdit({...edit,fecha:e.target.value})}/></label><label>Categoría<select value={edit.categoria} onChange={e=>setEdit({...edit,categoria:e.target.value})}>{['Salud','Educación','Cuidado','Otro'].map(c=><option key={c}>{c}</option>)}</select></label><label>Para quién<select value={edit.nino_id||''} onChange={e=>setEdit({...edit,nino_id:e.target.value})}><option value="">Toda la familia</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.primer_nombre} {p.apellidos}</option>)}</select></label><label>Responsable (opcional)<select value={edit.responsable_id||''} onChange={e=>setEdit({...edit,responsable_id:e.target.value})}><option value="">Sin asignar</option>{data.members.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select></label></div><label>Notas (opcional)<textarea maxLength={4000} value={edit.notas} onChange={e=>setEdit({...edit,notas:e.target.value})}/></label><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar recordatorio'}</button></form></Modal>}
    {remove&&<Modal title="Eliminar recordatorio" description={'¿Eliminar «'+remove.titulo+'»? Esta acción no se puede deshacer.'} close={()=>{if(!busy)setRemove(null);}}><ErrorNote error={error}/><button className="primary" disabled={busy} onClick={()=>void mutate('reminders/'+remove.id,'DELETE',{version:remove.version})}>{busy?'Eliminando…':'Confirmar eliminación'}</button></Modal>}
  </section>;
}
