import {useEffect,useState,type FormEvent} from 'react';
import {Settings2,Plus,ArrowUp,ArrowDown,Trash2,Save,ExternalLink} from 'lucide-react';
import {api} from './lib';
import {ErrorNote} from './components';
import {defaultSiteConfig} from '../shared/site-config.js';
import {notifySiteConfig,type SiteConfig} from './useSiteConfig';
import {BannerView} from './SiteBanner';
import './site-cms.css';
export default function SiteCMS(){
  const [config,setConfig]=useState<SiteConfig>(structuredClone(defaultSiteConfig)),[revision,setRevision]=useState(0),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  async function load(){setError('');try{const data=await api('platform/site-config');setConfig(data.config);setRevision(data.revision);setReady(true);}catch(e){setError((e as Error).message);}}
  useEffect(()=>{void load();},[]);
  function field(key:'hero_title'|'hero_subtitle'|'registration_cta',value:string){setConfig(c=>({...c,[key]:value}));setNotice('');}
  function move(index:number,direction:number){setConfig(c=>{const faqs=[...c.faqs];[faqs[index],faqs[index+direction]]=[faqs[index+direction],faqs[index]];return {...c,faqs};});}
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{const data=await api('platform/site-config','PUT',{config,revision});setConfig(data.config);setRevision(data.revision);notifySiteConfig();setNotice('Cambios guardados. La landing y la cabecera ya pueden leerlos sin un despliegue.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="site-cms"><div className="platform-page-heading"><div><p className="eyebrow">CONTENIDO PÚBLICO</p><h1><Settings2/> Configuración del sitio / CMS</h1><p className="muted">Solo administración de plataforma. No modifica datos de las familias.</p></div><a className="secondary" href="/presentacion" target="_blank" rel="noopener noreferrer"><ExternalLink size={16}/> Ver landing</a></div><ErrorNote error={error}/>{!ready?<button onClick={()=>void load()}>Cargar configuración</button>:<form onSubmit={save}><fieldset disabled={busy}>
    <section className="card"><h2>Landing page</h2><label className="field">Título principal<input required maxLength={140} value={config.hero_title} onChange={e=>field('hero_title',e.target.value)}/></label><label className="field">Subtítulo<textarea required maxLength={500} value={config.hero_subtitle} onChange={e=>field('hero_subtitle',e.target.value)}/></label><label className="field">Texto del botón de registro<input required maxLength={70} value={config.registration_cta} onChange={e=>field('registration_cta',e.target.value)}/></label><h3>Preguntas frecuentes</h3>{config.faqs.map((faq,index)=><div className="cms-faq" key={index}><label className="field">Pregunta {index+1}<input required maxLength={180} value={faq.question} onChange={e=>setConfig(c=>({...c,faqs:c.faqs.map((f,i)=>i===index?{...f,question:e.target.value}:f)}))}/></label><label className="field">Respuesta<textarea required maxLength={1500} value={faq.answer} onChange={e=>setConfig(c=>({...c,faqs:c.faqs.map((f,i)=>i===index?{...f,answer:e.target.value}:f)}))}/></label><div className="cms-actions"><button type="button" disabled={index===0} aria-label={`Subir pregunta ${index+1}`} onClick={()=>move(index,-1)}><ArrowUp size={16}/></button><button type="button" disabled={index===config.faqs.length-1} aria-label={`Bajar pregunta ${index+1}`} onClick={()=>move(index,1)}><ArrowDown size={16}/></button><button type="button" onClick={()=>setConfig(c=>({...c,faqs:c.faqs.filter((_,i)=>i!==index)}))}><Trash2 size={16}/> Quitar</button></div></div>)}<button type="button" disabled={config.faqs.length>=30} onClick={()=>setConfig(c=>({...c,faqs:[...c.faqs,{question:'',answer:''}]}))}><Plus size={16}/> Agregar pregunta</button></section>
    <section className="card"><h2>Banner global</h2><label className="cms-toggle"><input type="checkbox" role="switch" checked={config.banner.enabled} onChange={e=>setConfig(c=>({...c,banner:{...c.banner,enabled:e.target.checked}}))}/> Mostrar anuncio en la web y la app</label><label className="field">Tipo<select value={config.banner.type} onChange={e=>setConfig(c=>({...c,banner:{...c.banner,type:e.target.value}}))}><option value="info">Informativo</option><option value="warning">Advertencia</option><option value="promotion">Promoción</option></select></label><label className="field">Texto del anuncio<textarea required={config.banner.enabled} maxLength={300} value={config.banner.text} onChange={e=>setConfig(c=>({...c,banner:{...c.banner,text:e.target.value}}))}/></label><BannerView banner={config.banner}/></section>
    <section className="card"><h2>Contacto y redes sociales</h2><div className="cms-grid">{(['email','whatsapp','instagram','facebook','linkedin'] as const).map(key=><label className="field" key={key}>{({email:'Correo de contacto',whatsapp:'WhatsApp (con código de país)',instagram:'Instagram',facebook:'Facebook',linkedin:'LinkedIn'})[key]}<input type={key==='email'?'email':key==='whatsapp'?'tel':'url'} required={key==='email'} maxLength={key==='email'?254:key==='whatsapp'?16:500} placeholder={key==='whatsapp'?'+56912345678':key==='email'?'contacto@luspace.cl':'https://'} value={config.contact[key]} onChange={e=>setConfig(c=>({...c,contact:{...c.contact,[key]:e.target.value}}))}/></label>)}</div></section>
    <section className="card cms-draft"><h2>Vista previa del contenido sin guardar</h2><h3>{config.hero_title}</h3><p>{config.hero_subtitle}</p><span className="badge">{config.registration_cta}</span><p className="muted">El botón Guardar aplica los cambios a este entorno. Los campos admiten texto, no HTML.</p></section>
    <div className="cms-save"><button className="primary" type="submit"><Save size={17}/>{busy?'Guardando…':'Guardar cambios'}</button><button type="button" onClick={()=>{if(confirm('¿Descartar los cambios del formulario y recargar?'))void load();}}>Recargar datos guardados</button><span role="status">{notice}</span><small>Revisión {revision}</small></div>
  </fieldset></form>}</section>;
}
